# Generated by Django 4.0.1 on 2022-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('dob', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('profile', models.FileField(upload_to='profilephotos/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
