# Generated by Django 4.0.1 on 2022-03-19 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_registration_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('owneremail', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('images', models.FileField(upload_to='posts/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('likes', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
